Repository sparta-incubating/rchive-front-backoffice, pull requests merged in 2024-09, with the labels that each got.

#119 feat/ui: post 데이터 없을때 보여줄 페이지 작성 - empty page 작성 - 게시물 작성하기 button 작성
  src/components/atoms/category/postList.tsx
Labels: enhancement, style

#121 Fix/notion content fix
  package.json
  src/api/client/postApi.ts
  src/app/api/notion/content/route.ts
  src/components/atoms/postsTableRow.tsx
  src/components/pages/postDetail/postDetail.tsx
  src/utils/removeMarkDown.util.ts
Labels: bug, enhancement

#124 [#122] refactor: cicd 변경
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
Labels: enhancement

#125 fix: /로 접속시 /admin으로 이동시키는 로직 추가
  src/app/(rootLayout)/(backofficeLayout)/(home)/page.tsx
  src/components/atoms/authTimer.tsx
  src/components/atoms/category/adminSelectBoxCategory.tsx
  src/middleware.ts
  src/utils/clientAPI.ts
  src/utils/nextOptions/nextAuth.util.ts
Labels: bug, enhancement

#131 Update/rchive home button
  package.json
  src/components/molecules/postDetail/videoContainer.tsx
  src/components/organisms/backOfficeMenuBar.tsx
  yarn.lock
Labels: enhancement, update

#146 [#145]chore : 권한 승인/거절 단 건 선택 시 영역 수정
  src/app/(rootLayout)/(backofficeLayout)/admin/page.tsx
  src/components/atoms/category/adminSelectBoxCategory.tsx
Labels: bug

#148 [#147] update: notion content 받아오기 속도 개선
  package.json
  src/app/api/notion/content/route.ts
  src/components/atoms/postsTableRow.tsx
  src/components/molecules/post/postInputContainer.tsx
  src/components/molecules/postDetail/notionContainer.tsx
  src/hooks/usePostWriteForm.tsx
  src/utils/notion/notion.content.util.ts
  src/utils/notion/notionAPI.ts
Labels: enhancement, update

#151 Update/track name category
  src/api/client/categoryApi.ts
  src/api/client/postApi.ts
  src/api/profile/profileApi.ts
  src/api/profile/useQuery.ts
  src/api/server/postsApi.ts
  src/app/(rootLayout)/(backofficeLayout)/profile/page.tsx
  src/auth.ts
  src/class/postForm.ts
  src/components/atoms/category/postTapMenu.tsx
  src/components/atoms/postsTableRow.tsx
  src/components/molecules/post/postInfoContainer.tsx
  src/components/organisms/roleSelectForm.tsx
  src/components/pages/postListPage.tsx
  src/components/pages/profile/roleChangeModal.tsx
  src/components/pages/signIn.tsx
  src/hooks/useGetPeriod.ts
  src/hooks/usePostTypeNames.ts
  src/hooks/usePostWriteForm.tsx
  src/hooks/useSearchTutor.ts
  src/hooks/useTrackName.ts
  src/provider/compoundProvider.tsx
  src/redux/slice/auth.slice.ts
  src/types/auth.types.ts
  src/types/next-auth.d.ts
  src/types/posts.types.ts
  src/utils/nextOptions/nextAuth.util.ts
  src/utils/setAuthInfo/post.util.ts
  src/utils/setAuthInfo/setAuthInfo.tsx
  src/validators/auth/role.validator.ts
  src/validators/posts/posts.validator.ts
Labels: enhancement, update

#153 update: 게시물 작성시 tutor 입력 부분을 선택으로 변경
  src/components/atoms/selectItem.tsx
  src/components/atoms/tutorInput.tsx
  src/components/molecules/post/tutorContainer.tsx
  src/components/molecules/tutorCard.tsx
Labels: enhancement, update

#156 update: 게시물 작성
  src/hooks/usePostWriteForm.tsx
Labels: enhancement, update

#160 fix: 게시물 작성, 게시물 수정
  src/components/atoms/tutorInput.tsx
  src/components/molecules/post/postInfoContainer.tsx
  src/components/molecules/post/tutorContainer.tsx
  src/hooks/usePostWriteForm.tsx
  src/validators/posts/posts.validator.ts
Labels: bug, documentation, fix, feat

#162 fix: 게시물 작성 유효성검사 fix
  src/components/molecules/post/postInfoContainer.tsx
  src/components/molecules/post/tutorContainer.tsx
  src/hooks/usePostWriteForm.tsx
Labels: enhancement, fix, feat

#164 update: notion content 속도 개선
  src/utils/notion/notion.content.util.ts
  src/validators/posts/posts.validator.ts
Labels: enhancement, fix, feat

#166 [#165]Feat : 닉네임 백엔드에서 자동생성으로 회원가입 로직 수정
  src/api/admin/useMutation.ts
  src/api/profile/profileApi.ts
  src/class/signup.ts
  src/components/pages/profile/phoneChangeModal.tsx
  src/components/pages/signIn.tsx
  src/components/pages/signupModal.tsx
  src/hooks/useSignupForm.tsx
  src/validators/auth/signup.validator.ts
Labels: style, update

#170 [#169] fix: 게시물 등록 중 notion url이 오류날 경우 무한 로딩 되던 부분 개선
  src/api/client/postApi.ts
  src/components/atoms/category/postTableHeader.tsx
  src/components/atoms/postsTableRow.tsx
  src/hooks/usePostWriteForm.tsx
Labels: bug, enhancement, fix

#168 [#167] fix: dropdown focus out close
  src/components/atoms/category/AuthCategory.tsx
  src/components/atoms/category/adminSelectBoxCategory.tsx
  src/components/atoms/category/categoryContainer.tsx
  src/components/atoms/category/postFilterCategory.tsx
  src/components/atoms/category/postIsOpenSelectBoxCategory.tsx
  src/components/atoms/category/postIsOpenSelectBoxContainer.tsx
Labels: enhancement, fix

#173 [#155] Feat : admin 페이지 복합키 수정
  src/api/admin/adminApi.ts
  src/app/(rootLayout)/(backofficeLayout)/admin/page.tsx
  src/app/(rootLayout)/(backofficeLayout)/posts/[id]/page.tsx
  src/app/(rootLayout)/(backofficeLayout)/profile/page.tsx
  src/app/(rootLayout)/preview/page.tsx
  src/app/(rootLayout)/role/result/page.tsx
  src/components/atoms/admin/adminTableHeader.tsx
  src/components/atoms/backofficeHeaderTitle.tsx
  src/components/atoms/category/adminSelectBoxCategory.tsx
  src/components/atoms/category/postList.tsx
  src/components/atoms/category/postTapMenu.tsx
  src/components/atoms/category/tapMenu.tsx
  src/components/atoms/confirm.tsx
  src/components/atoms/inquiryButton.tsx
  src/components/atoms/permissionBoard.tsx
  src/components/atoms/searchBar.tsx
  src/components/atoms/uploadInput.tsx
  src/components/molecules/form/PhonChangeField.tsx
  src/components/molecules/form/PhoneField.tsx
  src/components/molecules/post/postInfoContainer.tsx
  src/components/molecules/post/thumbnailContainer.tsx
  src/components/molecules/post/tutorContainer.tsx
  src/components/organisms/backOfficeMenuBar.tsx
  src/components/organisms/postFormContainer.tsx
  src/components/organisms/profileChangeForm.tsx
  src/components/organisms/roleSelectForm.tsx
  src/components/pages/admin/AuthFilteredList.tsx
  src/components/pages/backofficePage.tsx
  src/components/pages/postListPage.tsx
  src/components/pages/profile/passwordChangeModal.tsx
  src/components/pages/profile/phoneChangeModal.tsx
  src/components/pages/profile/randomProfileModal.tsx
  src/components/pages/progressModal.tsx
  src/components/pages/signIn.tsx
  src/components/pages/signupModal.tsx
  src/components/pages/userInfo.tsx
  src/hooks/useSignupForm.tsx
  src/redux/slice/adminCheckBox.slice.ts
  src/styles/scrollbar.module.css
  src/styles/tagInput.module.css
  yarn.lock
Labels: bug, style, fix, update

#176 fix: tags validation 적용
  src/context/tag.context.tsx
  src/hooks/usePostWriteForm.tsx
Labels: bug, enhancement, fix

#177 [#175] Fix : map key 오류 수정
  src/app/(rootLayout)/(backofficeLayout)/admin/page.tsx
  src/components/atoms/category/AuthCategory.tsx
  src/components/molecules/form/PhonChangeField.tsx
  src/components/molecules/form/PhoneField.tsx
  src/components/pages/profile/phoneChangeModal.tsx
  src/hooks/useSignupForm.tsx
Labels: fix

#179 [#178] Fix/post max title
  src/components/molecules/post/postInputContainer.tsx
  src/validators/posts/posts.validator.ts
Labels: bug, enhancement, fix

#181 [#180] feat: 게시물 작성, 게시물 수정시 입력이 되면 뒤로가기, 새로고침, 다른 페이지 이동 confirm 출력
  src/components/organisms/postFormContainer.tsx
  src/hooks/usePageLeaveConfirm.tsx
  src/hooks/usePostWriteForm.tsx
Labels: enhancement, feat

#183 fix: 제목 50자로 제한 변경
  src/components/molecules/post/postInputContainer.tsx
  src/validators/posts/posts.validator.ts
Labels: enhancement, fix

#185 [#184] Fix : 유저테스트 피드백 반영
  src/app/(rootLayout)/(backofficeLayout)/admin/page.tsx
  src/components/atoms/category/adminSelectBoxCategory.tsx
  src/components/molecules/form/PhonChangeField.tsx
  src/components/molecules/form/PhoneField.tsx
  src/hooks/usePageLeaveConfirm.tsx
Labels: fix

#187 [#186]update : 휴대폰 번호 길이 수정
  src/components/molecules/form/PhonChangeField.tsx
  src/components/molecules/form/PhoneField.tsx
Labels: fix

#188 fix: 게시물 등록 submit일때는 confirm 건너뛰게 변경
  src/components/atoms/category/postList.tsx
  src/components/atoms/permissionBoard.tsx
  src/components/organisms/postFormContainer.tsx
  src/hooks/usePageLeaveConfirm.tsx
  src/hooks/usePostWriteForm.tsx
Labels: enhancement, fix

#193 fix: 게시물 등록, 수정 후 route cache 무력화
  src/app/(rootLayout)/(backofficeLayout)/posts/[id]/page.tsx
  src/app/actions/serverActions.ts
  src/hooks/usePostWriteForm.tsx
  src/types/posts.types.ts
Labels: bug, enhancement, fix

#195 feat : 문의하기 연결
  src/components/atoms/inquiryButton.tsx
  src/components/pages/roleResult/roleWait.tsx
  src/constants/helpLink.constant.ts
Labels: enhancement, feat

#205 fix: tag 등록시 공백은 등록못하게 변경
  src/context/tag.context.tsx
Labels: bug, enhancement, fix

#203 [#202] fix: login password 정규식 적용
  src/validators/auth/login.validator.ts
Labels: bug, enhancement, fix

#201 [#200] update: 게시물 리스트에서 썸네일 클릭시 디테일 페이지로 이동
  src/components/atoms/postsTableRow.tsx
Labels: enhancement, update

#199 [#198] update: 게시물 등록 tutor text style 변경
  src/components/molecules/post/postInputContainer.tsx
  src/components/molecules/post/tutorContainer.tsx
  src/components/molecules/tutorCard.tsx
Labels: enhancement, style, update

#211 210 tag작성시 제거
  src/context/tag.context.tsx
Labels: enhancement, update

#213 [#212]update : 로그인 메인 대시보드 이미지 수정
  public/assets/icons/back-dashboard.svg
  public/assets/icons/permission-rtan.svg
  src/components/pages/signIn.tsx
Labels: style

#216 [#215]fix: 게시물 리스트에서 각 filter 오류 수정
  src/components/atoms/category/postFilterCategory.tsx
  src/components/pages/postListPage.tsx
Labels: bug, enhancement, fix

#218 [#214]fix: notion 최신화 오류로 api url 변경
  src/api/client/postApi.ts
  src/components/atoms/postsTableRow.tsx
Labels: bug, enhancement, fix

#220 [#217] Fix : 시연 전 오류수정 작업
  src/components/atoms/category/tapMenu.tsx
  src/components/molecules/form/PhonChangeField.tsx
  src/components/pages/profile/roleChangeModal.tsx
Labels: update

#221 [#219]fix: 게시물 리스트 필터 초기화 등
  src/components/molecules/menuLinkCard.tsx
  src/components/organisms/backOfficeMenuBar.tsx
  src/components/pages/postListPage.tsx
Labels: bug, enhancement, fix

#223 [#222] Fix : 카테고리 선택 활성화 오류 수정
  src/components/atoms/category/AuthCategory.tsx
  src/components/atoms/category/postFilterCategory.tsx
  src/components/pages/admin/categoryFiltered.tsx
Labels: bug, style
