Repository sparta-incubating/rchive-front-backoffice, pull requests merged in 2024-07, with the labels that each got.

#1 #3 UI(button Design): 재사용가능한 button component 완성
  package.json
  src/app/(rootLayout)/(home)/page.tsx
  src/components/atoms/button.tsx
  src/lib/utils.ts
  yarn.lock
Labels: documentation, enhancement, style

#10 UI/add design system 3
  package.json
  public/assets/icons/checkBlue.svg
  public/assets/test/img.png
  src/app/(rootLayout)/(home)/page.tsx
  src/app/(rootLayout)/layout.tsx
  src/app/(rootLayout)/uiComponents/page.tsx
  src/app/api/og-image/route.ts
  src/app/globals.css
  src/components/atoms/button.tsx
  src/components/atoms/selectContainer.tsx
  src/components/atoms/selectInput.tsx
  src/components/atoms/uploadInput.tsx
  src/components/atoms/uploadThumbnail.tsx
  src/components/atoms/uploadThumbnailText.tsx
  src/components/molecules/toast.tsx
  src/components/molecules/uploadContainer.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/components/ui/checkbox.tsx
  src/hooks/useDebounce.ts
  src/types/utils.types.ts
  src/utils/reduxHooks.ts
  src/utils/toast.ts
  src/utils/utils.ts
  yarn.lock
Labels: enhancement

#11 [#4] UI(SignUp) : 회원가입 Feild UI작업
  .eslintrc.cjs
  .vscode/settings.json
  src/app/(rootLayout)/uiComponents/page.tsx
  src/app/globals.css
  src/components/Molecules/InputField.tsx
  src/components/Molecules/form/BirthdayForm.tsx
  src/components/Molecules/form/EmailForm.tsx
  src/components/Molecules/form/NameForm.tsx
  src/components/Molecules/form/PasswordForm.tsx
  src/components/Molecules/form/PhoneField.tsx
  src/components/Molecules/form/PhoneForm.tsx
  src/components/Templetes/page.tsx
  src/components/atoms/InputContainer.tsx
  src/components/atoms/PasswordContainer.tsx
  src/components/atoms/label.tsx
  src/components/atoms/span.tsx
  src/components/organisms/selectBox.tsx
  tailwind.config.ts
Labels: enhancement, style

#20 [#15] Style : 변경된 로그인 UI 1차 수정 완료
  public/assets/icons/board-rtan.svg
  public/assets/icons/dashboard.svg
  public/assets/icons/permissions-rtan.svg
  public/assets/icons/siginIn-rtan.svg
  public/assets/icons/write-rtan.svg
  src/app/(rootLayout)/(home)/page.tsx
  src/components/pages/signIn.tsx
  tailwind.config.ts
Labels: style

#32 [#31] Fix : 로그인 기능 구현
  .env.template
  package.json
  public/assets/icons/permission-rtan.svg
  public/assets/icons/sign-rtan.svg
  src/app/(rootLayout)/(backofficeLayout)/(home)/page.tsx
  src/app/(rootLayout)/(backofficeLayout)/layout.tsx
  src/app/(rootLayout)/layout.tsx
  src/app/(rootLayout)/login/page.tsx
  src/app/layout.tsx
  src/components/atoms/menubarLogout.tsx
  src/components/pages/signIn.tsx
  src/middleware.ts
  src/types/login.types.ts
  src/types/next-auth.d.ts
  src/utils/clientAPI.ts
  src/validators/auth/login.validator.ts
  yarn.lock
Labels: bug, enhancement, question

#44 feat:게시물 api 연결
  src/api/postApi.ts
  src/components/atoms/modal.tsx
  src/components/molecules/post/postInfoContainer.tsx
  src/components/molecules/post/tutorContainer.tsx
  src/components/pages/progressModal.tsx
  src/hooks/usePostWriteForm.tsx
  src/types/posts.types.ts
  src/validators/posts/posts.validator.ts
Labels: documentation, enhancement
