Repository sparta-incubating/rchive-front-backoffice, pull requests merged in 2024-08, with the labels that each got.

#48 트랙 및 기수 선택 기능
  src/api/authApi.ts
  src/app/(rootLayout)/(backofficeLayout)/(home)/page.tsx
  src/app/(rootLayout)/role/page.tsx
  src/app/(rootLayout)/role/result/page.tsx
  src/components/atoms/dropDownItem.tsx
  src/components/atoms/modal.tsx
  src/components/atoms/selectDumyItem.tsx
  src/components/molecules/dropDownContainer.tsx
  src/components/molecules/post/postInfoContainer.tsx
  src/components/molecules/post/thumbnailContainer.tsx
  src/components/molecules/signupHeader.tsx
  src/components/organisms/roleSelectForm.tsx
  src/components/pages/roleContainerPage.tsx
  src/components/pages/roleResult/roleWait.tsx
  src/components/pages/signIn.tsx
  src/components/pages/signUpCompleteModal.tsx
  src/components/pages/signupModal.tsx
  src/components/pages/signupTest.tsx
  src/hooks/useGetPeriod.ts
  src/hooks/useSignupForm.tsx
  src/types/auth.types.ts
  src/types/posts.types.ts
  src/types/role.types.ts
  src/utils/clientAPI.ts
  src/utils/utils.ts
  src/validators/auth/role.validator.ts
  src/validators/commons.ts
  src/validators/posts/posts.validator.ts
Labels: documentation, enhancement, style

#57 fix: 권한 승인 후 거부 시 오류 수정
  src/api/authApi.ts
  src/app/(rootLayout)/role/result/page.tsx
  src/components/pages/roleResult/roleWait.tsx
  src/components/pages/signIn.tsx
  src/utils/auth.util.ts
  src/utils/clientAPI.ts
Labels: documentation, enhancement

#61 fix: middleware 권한 체크 변경 및 server side 로직 변경
  src/api/authApi.ts
  src/app/(rootLayout)/role/result/page.tsx
  src/app/api/auth/lastConnectRole/route.ts
  src/app/api/auth/login/route.ts
  src/components/pages/roleResult/roleWait.tsx
  src/components/pages/signIn.tsx
  src/middleware.ts
  src/utils/auth.server.util.ts
  src/utils/serverAPI.ts
Labels: documentation

#71 [#70] Fix : 백엔드 배포 오류 수정작업
  src/app/api/notion/content/route.ts
  src/app/layout.tsx
  src/components/atoms/tagInput.tsx
  src/components/atoms/uploadThumbnailText.tsx
  src/components/molecules/post/uploadContainer.tsx
  src/components/molecules/signupHeader.tsx
  src/components/organisms/backOfficeMenuBar.tsx
  src/components/organisms/tagContainer.tsx
  src/components/pages/signIn.tsx
  src/components/pages/signUpCompleteModal.tsx
  src/components/ui/button.tsx
  src/components/ui/buttonVariants.ts
  src/context/modal.context.tsx
  src/context/tag.context.tsx
  src/context/useModalContext.ts
  src/context/useTagContext.ts
  src/hooks/usePostWriteForm.tsx
  src/hooks/useSignupForm.tsx
Labels: bug

#69 [#67] chore: cicd 구성중
  .github/workflows/ci-dev.yml
  .github/workflows/ci-prod.yml
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
  Dockerfile
Labels: enhancement

#78 [#67] CICD: cicd-prod 변경
  .github/workflows/cicd-prod.yml
Labels: enhancement

#79 [#76] dev to main
  .github/workflows/cicd-prod.yml
Labels: release

#83 feat: login
  src/app/(rootLayout)/(backofficeLayout)/(home)/_components/testComponent.tsx
  src/app/(rootLayout)/(backofficeLayout)/(home)/page.tsx
  src/app/api/auth/reissue/route.ts
  src/auth.ts
Labels: documentation, enhancement

#88 refactor(CICD): CI 성능개선
  .github/workflows/ci-dev.yml
  .github/workflows/ci-prod.yml
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
Labels: enhancement

#90 [#87] refactor: CICD 성능개선
  .dockerignore
  .github/workflows/ci-dev.yml
  .github/workflows/ci-prod.yml
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
  Dockerfile
Labels: enhancement

#91 [#87] refactor: CICD 성능개선
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
Labels: enhancement

#92 [#87] refactor: CICD 성능개선
  .dockerignore
Labels: enhancement

#93 [#87] refactor: cicd 성능개선
  .dockerignore
Labels: enhancement

#94 [#76] Release: release ver1.0
  .dockerignore
  .github/workflows/ci-dev.yml
  .github/workflows/ci-prod.yml
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
  Dockerfile
  package.json
  src/api/authApi.ts
  src/api/client/authApi.ts
  src/api/client/postApi.ts
  src/api/server/authApi.ts
  src/app/(rootLayout)/(backofficeLayout)/(home)/_components/testComponent.tsx
  src/app/(rootLayout)/(backofficeLayout)/(home)/page.tsx
  src/app/(rootLayout)/(backofficeLayout)/posts/page.tsx
  src/app/(rootLayout)/role/result/page.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/auth/lastConnectRole/route.ts
  src/app/api/auth/login/route.ts
  src/app/api/auth/reissue/route.ts
  src/auth.config.ts
  src/auth.ts
  src/components/atoms/customError.tsx
  src/components/atoms/menubarLogout.tsx
  src/components/atoms/postsTableRow.tsx
  src/components/molecules/post/thumbnailContainer.tsx
  src/components/molecules/post/tutorContainer.tsx
  src/components/organisms/backOfficeMenuBar.tsx
  src/components/organisms/roleSelectForm.tsx
  src/components/pages/postListPage.tsx
  src/components/pages/roleResult/roleResult.tsx
  src/components/pages/roleResult/roleWait.tsx
  src/components/pages/signIn.tsx
  src/components/pages/userInfo.tsx
  src/constants/auth.constant.ts
  src/context/tag.context.tsx
  src/hooks/useGetPeriod.ts
  src/hooks/usePostIsOpenUpdate.ts
  src/hooks/usePostWriteForm.tsx
  src/hooks/useSearchTutor.ts
  src/hooks/useServerComponentErrorHandling.ts
  src/hooks/useSignupForm.tsx
  src/middleware.ts
  src/provider/compoundProvider.tsx
  src/provider/nextAuthProvider/nextAuthProvider.tsx
  src/types/next-auth.d.ts
  src/utils/auth.server.util.ts
  src/utils/auth.util.ts
  src/utils/axiosAPI.ts
  src/utils/clientAPI.ts
  src/utils/nextOptions/nextAuth.ts
  src/utils/nextOptions/nextAuth.util.ts
  src/utils/serverAPI.ts
  yarn.lock
Labels: release

#99 [#98] refactor: cicd 수정
  .github/workflows/cicd-prod.yml
Labels: enhancement

#108 fix: preview tag ui 변경
  src/components/molecules/postDetail/postDetailTag.tsx
  src/components/organisms/postFormContainer.tsx
Labels: bug

#109 Fix/refresh token update
  next.config.mjs
  src/api/client/postApi.ts
  src/api/server/postsApi.ts
  src/app/(rootLayout)/(backofficeLayout)/posts/page.tsx
  src/app/api/auth/reissue/route.ts
  src/auth.ts
  src/components/atoms/customError.tsx
  src/components/organisms/preview/previewContainer.tsx
  src/hooks/useServerComponentErrorHandling.ts
  src/provider/compoundProvider.tsx
Labels: bug

#104 [#95] : 랜덤 프로필 API 수정 및 회원가입 시 휴대폰인증 기능 추가
  public/assets/icons/MRT_1.svg
  src/api/client/authApi.ts
  src/api/profile/profileApi.ts
  src/app/(rootLayout)/(backofficeLayout)/admin/page.tsx
  src/app/(rootLayout)/(backofficeLayout)/profile/page.tsx
  src/class/signup.ts
  src/components/molecules/InputField.tsx
  src/components/molecules/form/PhoneField.tsx
  src/components/molecules/form/PhoneForm.tsx
  src/components/molecules/profileContainer.tsx
  src/components/organisms/postFormContainer.tsx
  src/components/pages/admin/categoryFiltered.tsx
  src/components/pages/profile/randomProfileModal.tsx
  src/components/pages/profile/roleChangeModal.tsx
  src/components/pages/signIn.tsx
  src/components/pages/signupModal.tsx
  src/components/pages/userInfo.tsx
  src/hooks/useSignupForm.tsx
  src/types/profile.types.ts
  src/types/signup.types.ts
  src/utils/clientAPI.ts
  src/validators/auth/signup.validator.ts
Labels: enhancement

#112 [#105] feat : 헬퍼테스트 및 버그 해결
  src/api/client/authApi.ts
  src/app/(rootLayout)/(backofficeLayout)/admin/page.tsx
  src/components/atoms/authTimer.tsx
  src/components/atoms/category/tapMenu.tsx
  src/components/atoms/selectInput.tsx
  src/components/molecules/form/PhoneField.tsx
  src/components/molecules/menuLinkCard.tsx
  src/components/organisms/profileChangeForm.tsx
  src/components/pages/signIn.tsx
  src/components/pages/signupModal.tsx
  src/hooks/useSignupForm.tsx
  src/types/admin.types.ts
  src/validators/auth/login.validator.ts
  src/validators/auth/signup.validator.ts
Labels: bug, enhancement, style

#114 fix : path 변경
  src/api/client/authApi.ts
  src/api/client/postApi.ts
  src/app/(rootLayout)/(backofficeLayout)/(home)/page.tsx
  src/app/(rootLayout)/backoffice/(backofficeLayout)/(home)/_components/testComponent.tsx
  src/app/(rootLayout)/backoffice/(backofficeLayout)/(home)/page.tsx
  src/app/(rootLayout)/backoffice/(backofficeLayout)/admin/page.tsx
  src/app/(rootLayout)/backoffice/(backofficeLayout)/layout.tsx
  src/app/(rootLayout)/backoffice/(backofficeLayout)/posts/[id]/page.tsx
  src/app/(rootLayout)/backoffice/(backofficeLayout)/posts/page.tsx
  src/app/(rootLayout)/backoffice/(backofficeLayout)/posts/write/page.tsx
  src/app/(rootLayout)/backoffice/(backofficeLayout)/profile/page.tsx
  src/app/(rootLayout)/backoffice/login/page.tsx
  src/app/(rootLayout)/backoffice/preview/page.tsx
  src/app/(rootLayout)/backoffice/role/page.tsx
  src/app/(rootLayout)/backoffice/role/result/page.tsx
  src/app/(rootLayout)/backoffice/uiComponents/page.tsx
  src/app/api/backoffice/auth/[...nextauth]/route.ts
  src/app/api/backoffice/auth/lastConnectRole/route.ts
  src/app/api/backoffice/auth/login/route.ts
  src/app/api/backoffice/auth/reissue/route.ts
  src/app/api/backoffice/notion/content/route.ts
  src/app/api/backoffice/notion/database/route.ts
  src/app/api/backoffice/notion/page/route.ts
  src/app/api/backoffice/notion/webShare/route.ts
  src/app/api/backoffice/og-image/route.ts
  src/auth.config.ts
  src/components/atoms/backofficeHeaderTitle.tsx
  src/components/atoms/postsTableRow.tsx
  src/components/molecules/post/thumbnailContainer.tsx
  src/components/molecules/post/uploadContainer.tsx
  src/components/molecules/postDetail/notionContainer.tsx
  src/components/organisms/menubarLinks.tsx
  src/components/organisms/postFormContainer.tsx
  src/components/pages/postListPage.tsx
  src/components/pages/signIn.tsx
  src/constants/backoffcicePath.constant.ts
  src/hooks/usePostWriteForm.tsx
  src/hooks/useServerComponentErrorHandling.ts
  src/middleware.ts
  src/provider/nextAuthProvider/nextAuthProvider.tsx
  src/utils/clientAPI.ts
  src/utils/notionAPI.ts
  src/utils/setAuthInfo/setAuthInfo.tsx
Labels: enhancement, fix

#116 [#115] refactor: CICD 수정
  .github/workflows/cicd-dev.yml
Labels: enhancement
